#!/bin/bash
#SBATCH --ntasks=1
#SBATCH -A delbruck.ini.uzh
#SBATCH --partition=volta
#SBATCH --time=24:0:0
#SBATCH --mem-per-cpu=14000
#SBATCH --array=1-80
#SBATCH --gres gpu:Tesla-V100:1 --mem=14000
#SBATCH --output=/data/jlungu/exp-logs/fconv-en2cn-run-%a.log
#SBATCH --error=/data/jlungu/exp-logs/fconv-en2cn-run-%a.log

source activate siamese
cd /data/jlungu/siamese_on_edge/tasks

make run-${SLURM_ARRAY_TASK_ID}-siamese_exps
